### ISSUE TITLE
Fractional widths

### ISSUE THREAD

**Issue by richcorbs** [stevebauman/curlwind#1]
Love what you've done with CurlWind. The website is awesome.

I was just trying to use CurlWind and discovered that "w-\*" does not return "w-1/3" or other fractional widths. Maybe "h-\*" is the same.

When I tried explicitly adding "w-1/3" it returned a 422.

Hope this helps. I just found the repo. I'll look around and see if I can contribute

Thanks for CurlWind!

**Comment by stevebauman** [comment]
Hi @richcorbs!

Shoot you're totally right, I think it's excluded from the allowed regex! I'll update it tomorrow morning and close this out once deployed.

Appreciate the heads up! 🙏

**Comment by stevebauman** [comment]
Fixed in the latest update, thanks!
