### ISSUE TITLE
Tailwind Plugins

### ISSUE THREAD

**Issue by vacmar01** [stevebauman/curlwind#5]
Hey there, 

first thanks for this awesome project. 

Does curlwind support tailwind plugins, like typography? 

Cheers 

Marius

**Comment by stevebauman** [comment]
Hey @vacmar01!

I think I should actually enable all of them by default so they can be enabled in the query params.

Let me get that working 👍

**Comment by vacmar01** [comment]
That was very fast! Thank you, will try it out ☺️

**Comment by stevebauman** [comment]
Happy to help @vacmar01! 🙏
