### ISSUE TITLE
Multiple links to curlwind on a page?

### ISSUE THREAD

**Issue by richcorbs** [stevebauman/curlwind#7]
This really isn't an issue but it seemed more than I wanted to ask on X.

How terrible would it be to include multiple links to cdn.curlwind.com on a page?

Even for a small page there could be a lot of styles. Think of the lengthy tailwind class lists on individual elements and then needing to combine all of them (the unique ones) together into a single URL. I mean we only get 2048 characters, depending on which source and browser you trust.

I'm considering having links for:

- typography
- spacing
- layout
- colors

Would that just be awful from any perspective?

Thanks for CurlWind! It's enjoyable to use.

**Comment by stevebauman** [comment]
Hey @richcorbs, thanks for the question!

I don't think it'd be awful at all, it'd just be an additional HTTP request on the initial load of the page.

I totally get it though. I'm thinking of building a "preset" system where you'll be able to toggle on styles and combine them into a single shortlink.

Also thinking of implementing the ability to provide "categories" or "properties" in the query params to produce the tailwind classes that interact with said category or properties. For example, passing in "properties=flex" would produce all the Tailwind flexbox utilities.

What do you think?

**Comment by richcorbs** [comment]
Just tried out multiple links. It seems to have worked.

The only observation so far is that every link returned a fair amount of boilerplate tailwind stuff beyond the things I explicitly asked for. I don't think this reflects negatively on CurlWind. Just an observation.

With separate links I get back ~16kb in CSS. It happens largely in parallel and so it's still snappy.

With one big link I only get back ~7kb.

**Comment by richcorbs** [comment]
Would presets be configurable by some sort of UI? And name-able? Like gimme the "?preset-name=project-x-typography-styles"?

I can see the value of having "properties".

On the other hand, a CurlWind without support for wildcards would force me to request exactly what I need which kind of matches the minimalistic vibe I get when I use CurlWind.

Thanks for being approachable about it!

**Comment by stevebauman** [comment]
Ah you'll likely receiving Tailwinds "preflight" CSS in both of them. Disable it on one of the links via "preflight=0"

**Comment by stevebauman** [comment]
> Would presets be configurable by some sort of UI? And name-able? Like gimme the "?preset-name=project-x-typography-styles"?

Yea that's exactly right 👍

**Comment by richcorbs** [comment]
Here's where I ended tonight:

- I split my styles in 5 links with only the specific classes I need, no wildcards.
- The largest is 2.7k (with preflight) and the others are all under 2k.
- The 5 requests are made in parallel and all come back in under 200ms.
