### ISSUE TITLE
CDN response is not being cached

### ISSUE THREAD

**Issue by Christopher-Warren** [stevebauman/curlwind#8]
Hey there, it appears that the CDN link is not allowing the browser to cache the data, whereas the official tailwind CDN caches the response. Is this intentional, or am I missing something? 
![image](https://github.com/stevebauman/curlwind/assets/21307317/0540850b-9a52-4d29-8be5-eb767e078eca)

As seen below the `cache-control` response header is being set as `no-cache, private`
![image](https://github.com/stevebauman/curlwind/assets/21307317/f868f3a6-1388-48a9-ae30-05c6f0b870f2)

**Comment by stevebauman** [comment]
Whoops, you're right, this should be changed, thanks for the report!

**Comment by stevebauman** [comment]
Deployed, should be fixed now -- have a pretty aggressive cache on it now (one year, public) 👍 

Appreciate the detailed issue 🙏

**Comment by Christopher-Warren** [comment]
Works like a charm. 🙏 I appreciate the work you put into this!

**Comment by stevebauman** [comment]
Awesome! And thanks @Christopher-Warren! 🙏
